// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package page_shop_frags

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func FilterMenu() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<dialog id=\"filter-menu\" onclick=\"CloseFilterMenu(event)\"><div style=\"max-width: 0; max-height: 0; overflow: hidden;\"><input autofocus=\"true\"></div><h1 id=\"filter-group-text\">Filter Options</h1><span class=\"filter-group-title\">Brands</span><div id=\"brands_filters\"><input type=\"text\" id=\"brand-search-input\" placeholder=\"Search a brand\" oninput=\"DebouncBrandFilterSuggestionCall()\"> <span class=\"title\">Suggestions</span><ul id=\"suggestions-holder\" hx-get=\"/components/filtersSuggestions\" hx-vals=\"js:{brands: FILTERS.brands}\" hx-trigger=\"load\" hx-swap=\"innerHTML\"></ul><hr><span class=\"title\">Selecteds</span><ul id=\"selecteds-holder\"></ul></div><h2 class=\"filter-group-title\">Price</h2>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = priceRange().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
