// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package page_shop_frags

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func FilterMenu() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"filter-menu\"><h2>Filter Options</h2><ul id=\"brands_filter\"><span>Marcas</span> <label><input type=\"checkbox\" name=\"brand\" value=\"Corona\" onchange=\"DeboucingFiltersConstUpdate()\"> <span>Corona</span></label> <label><input type=\"checkbox\" name=\"brand\" value=\"Heineken\" onchange=\"DeboucingFiltersConstUpdate()\"> <span>Heineken</span></label> <label><input type=\"checkbox\" name=\"brand\" value=\"Super BOCK\" onchange=\"DeboucingFiltersConstUpdate()\"> <span>Super BOCK</span></label> <label><input type=\"checkbox\" name=\"brand\" value=\"Skol\" onchange=\"DeboucingFiltersConstUpdate()\"> <span>Skol</span></label> <label><input type=\"checkbox\" name=\"brand\" value=\"Itaipava\" onchange=\"DeboucingFiltersConstUpdate()\"> <span>Itaipava</span></label> <label><input type=\"checkbox\" name=\"brand\" value=\"Glacial\" onchange=\"DeboucingFiltersConstUpdate()\"> <span>Glacial</span></label></ul><h2>Price</h2>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = priceRange().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
